In [25]:
import pandas as pd
df = pd.read_csv('C:/Users/DELL/Desktop/amazon fine review/amazon fine fode/Reviews.csv')

In [26]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Text          568454 non-null  object
 1   Score         568454 non-null  int64
 2   Sentiment     568454 non-null  object
 3   Cleaned_Text  568454 non-null  object
dtypes: int64(1), object(3)
memory usage: 17.3+ MB

In [ ]:
df = df[['Text', 'Score']]
def classify_sentiment(score):
    if score <= 2:
        return 'Negative'
    elif score == 3:
        return 'Neutral'
    else:
        return 'Positive'

df['Sentiment'] = df['Score'].apply(classify_sentiment)

convert the text into lowercase

In [28]:
df['Cleaned_Text'] = df['Text'].str.lower()

In [29]:
df.head()

,Text,Score,Sentiment,Cleaned_Text
0,I have bought several of the Vitality canned d...,5,Positive,i have bought several of the vitality canned d...
1,Product arrived labeled as Jumbo Salted Peanut...,1,Negative,product arrived labeled as jumbo salted peanut...
2,This is a confection that has been around a fe...,4,Positive,this is a confection that has been around a fe...
3,If you are looking for the secret ingredient i...,2,Negative,if you are looking for the secret ingredient i...
4,Great taffy at a great price. There was a wid...,5,Positive,great taffy at a great price. there was a wid...

remove  punctuation

In [31]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans("", "", string.punctuation))

df['Cleaned_Text'] = df['Cleaned_Text'].apply(remove_punctuation)

In [32]:
df.head()

,Text,Score,Sentiment,Cleaned_Text
0,I have bought several of the Vitality canned d...,5,Positive,i have bought several of the vitality canned d...
1,Product arrived labeled as Jumbo Salted Peanut...,1,Negative,product arrived labeled as jumbo salted peanut...
2,This is a confection that has been around a fe...,4,Positive,this is a confection that has been around a fe...
3,If you are looking for the secret ingredient i...,2,Negative,if you are looking for the secret ingredient i...
4,Great taffy at a great price. There was a wid...,5,Positive,great taffy at a great price there was a wide...

remove of stopwords

In [39]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return " ".join(word for word in text.split() if word not in stop_words)

df['Cleaned_Text'] = df['Cleaned_Text'].apply(remove_stopwords)

LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - 'C:\\Users\\DELL/nltk_data'
    - 'c:\\ProgramData\\anaconda3\\nltk_data'
    - 'c:\\ProgramData\\anaconda3\\share\\nltk_data'
    - 'c:\\ProgramData\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\DELL\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

remove_frequent_word

In [ ]:
from collections import Counter
word_counts = Counter(" ".join(df['Cleaned_Text']).split())
frequent_words = set([word for word, count in word_counts.items() if count > 100])

def remove_frequent_words(text):
    return " ".join(word for word in text.split() if word not in frequent_words)

df['Cleaned_Text'] = df['Cleaned_Text'].apply(remove_frequent_words)
df.head()

,Text,Score,Sentiment,Cleaned_Text
0,I have bought several of the Vitality canned d...,5,Positive,
1,Product arrived labeled as Jumbo Salted Peanut...,1,Negative,peanutsthe
2,This is a confection that has been around a fe...,4,Positive,pillowy filberts lewis witch wardrobe seduces ...
3,If you are looking for the secret ingredient i...,2,Negative,robitussin
4,Great taffy at a great price. There was a wid...,5,Positive,

remove of rarewords

In [43]:
rare_words = set([word for word, count in word_counts.items() if count == 1])

def remove_rare_words(text):
    return " ".join(word for word in text.split() if word not in rare_words)

df['Cleaned_Text'] = df['Cleaned_Text'].apply(remove_rare_words)
df

,Text,Score,Sentiment,Cleaned_Text
0,I have bought several of the Vitality canned d...,5,Positive,
1,Product arrived labeled as Jumbo Salted Peanut...,1,Negative,peanutsthe
2,This is a confection that has been around a fe...,4,Positive,pillowy filberts lewis witch wardrobe seduces ...
3,If you are looking for the secret ingredient i...,2,Negative,robitussin
4,Great taffy at a great price. There was a wid...,5,Positive,
...,...,...,...,...
568449,Great for sesame chicken..this is a good if no...,5,Positive,chickenthis resturants itwill
568450,I'm disappointed with the flavor. The chocolat...,2,Negative,disappoints
568451,"These stars are small, so you can give 10-15 o...",5,Positive,ceaser
568452,These are the BEST treats for training and rew...,5,Positive,grooming
568453,"I am very satisfied ,product is as advertised,...",5,Positive,

remove of special_characters

In [44]:
import re

def remove_special_characters(text):
    return re.sub(r"[^a-zA-Z0-9\s]", "", text)

df['Cleaned_Text'] = df['Cleaned_Text'].apply(remove_special_characters)
df

,Text,Score,Sentiment,Cleaned_Text
0,I have bought several of the Vitality canned d...,5,Positive,
1,Product arrived labeled as Jumbo Salted Peanut...,1,Negative,peanutsthe
2,This is a confection that has been around a fe...,4,Positive,pillowy filberts lewis witch wardrobe seduces ...
3,If you are looking for the secret ingredient i...,2,Negative,robitussin
4,Great taffy at a great price. There was a wid...,5,Positive,
...,...,...,...,...
568449,Great for sesame chicken..this is a good if no...,5,Positive,chickenthis resturants itwill
568450,I'm disappointed with the flavor. The chocolat...,2,Negative,disappoints
568451,"These stars are small, so you can give 10-15 o...",5,Positive,ceaser
568452,These are the BEST treats for training and rew...,5,Positive,grooming
568453,"I am very satisfied ,product is as advertised,...",5,Positive,